apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netcore-demo
  template:
    metadata:
      labels:
        app: netcore-demo
    spec:
      containers:
      - name: netcore-demo
        image: ashwilliams/netcore-upload:arov1
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: "0.5"
            memory: 750Mi
        ports:
        - containerPort: 8080
        env:
        - name: GitHub
          value: "https://github.com/AshWilliams/NetCoreUpload"      
        volumeMounts:
        - name: images-premium-storage
          mountPath: /app/wwwroot/images
      volumes:
      - name: images-premium-storage
        persistentVolumeClaim:
          claimName: az-file-pvc3
