apiVersion: v1
kind: Service
metadata:
  name: svc-netcore-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: netcore-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcore-demo
  template:
    metadata:
      labels:
        app: netcore-demo
    spec:
      containers:
      - name: netcore-demo
        image: ashwilliams/netcore-upload:v8
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: "0.5"
            memory: 750Mi
        ports:
        - containerPort: 80
        env:
        - name: GitHub
          value: "https://github.com/AshWilliams/NetCoreUpload"      
        - name: Logo
          value: "https://preview.redd.it/erdjqzlmlv111.png?auto=webp&s=1dfcc14e586e2aaa0ee7fb9a1bb9da6679ec892b" 
      #   volumeMounts:
      #   - name: images-premium-storage
      #     mountPath: /app/wwwroot/images
      # volumes:
      # - name: images-premium-storage
      #   persistentVolumeClaim:
      #     claimName: images-premium-storage
